# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{

  flake.nixosModules.laptopHardware = { config, lib, pkgs, modulesPath, ... }: {
    imports = [ 
      (modulesPath + "/profiles/qemu-guest.nix") 
    ];

    boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "virtio_pci" "sr_mod" "virtio_blk" ];
    boot.initrd.kernelModules = [ ];
    boot.kernelModules = [ "kvm-intel" ];
    boot.extraModulePackages = [ ];

    # Commented out these file paths portions though this file is usually not edited, because disko
    # is managing the file structure declaratively instead.
    #
    # fileSystems."/" =
    #   { device = "/dev/disk/by-uuid/24b2d2d4-1f4f-4e3d-b930-a273ee3760b5";
    #     fsType = "ext4";
    #   };
    #
    # swapDevices =
    #   [ { device = "/dev/disk/by-uuid/4f73acdd-19ff-4e09-858a-4dd222ab4355"; }
    #   ];

    # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
    # (the default) this is the recommended approach. When using systemd-networkd it's
    # still possible to use this option, but it's recommended to use it in conjunction
    # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
    networking.useDHCP = lib.mkDefault true;
    # networking.interfaces.enp1s0.useDHCP = lib.mkDefault true;

    nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  };
}
