# Simply edit the file path to the wallpaper,
# and set the monitor output to match your setup.
# Use `hyprctl monitors` to get the correct data.
preload = ~/Pictures/wallpapers/metropolis.png
wallpaper = Virtual-1,~/Pictures/wallpapers/metropolis.png
ipc = on
